# Generated by Django 5.0.1 on 2024-02-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='ingredients',
            field=models.TextField(null=True),
        ),
    ]
