# Generated by Django 5.0.1 on 2024-02-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='ingredients',
        ),
    ]
