# Generated by Django 5.0.1 on 2024-02-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0005_remove_ingredient_food_foods_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='foods',
            name='ingredient',
            field=models.ManyToManyField(to='res.ingredient'),
        ),
    ]
