# Generated by Django 5.0.1 on 2024-02-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0007_remove_foods_ingredient_ingredient_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='food',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='food',
            field=models.ManyToManyField(to='res.foods'),
        ),
    ]
