# Generated by Django 5.0.1 on 2024-02-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0011_remove_foods_categorymenu_foods_categorymenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
