# Generated by Django 5.0.1 on 2024-02-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0012_alter_foods_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='description',
            field=models.TextField(),
        ),
    ]
