# Generated by Django 5.0.1 on 2024-02-09 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0014_remove_foods_categorymenu_foods_categorymenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='foods',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='res.ingredient'),
        ),
    ]
