# Generated by Django 5.0.1 on 2024-02-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0015_remove_foods_ingredient_foods_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='ingredient',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
