# Generated by Django 5.0.1 on 2024-02-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0016_alter_foods_ingredient_delete_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='ingredient',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
