# Generated by Django 5.0.1 on 2024-02-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0017_alter_foods_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='ingredient',
            field=models.TextField(null=True),
        ),
    ]
