# Generated by Django 5.0.1 on 2024-02-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0018_alter_foods_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
