# Generated by Django 5.0.1 on 2024-02-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0019_rename_ingredient_foods_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='ingredients',
            new_name='ingredient_id',
        ),
    ]
