# Generated by Django 5.0.1 on 2024-02-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0020_rename_ingredients_foods_ingredient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='ingredient_id',
            new_name='ingredients',
        ),
    ]
