# Generated by Django 5.0.1 on 2024-02-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0021_rename_ingredient_id_foods_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='foods',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='foods',
            name='ingredient',
            field=models.ManyToManyField(to='res.ingredient'),
        ),
    ]
