# Generated by Django 5.0.1 on 2024-02-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0023_foodsingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodsingredient',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='foodsingredient',
            name='ingredients',
            field=models.ManyToManyField(to='res.ingredient'),
        ),
    ]
