# Generated by Django 5.0.1 on 2024-02-10 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0028_remove_foods_ingredient_ingredient_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='ingredient',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='categorymenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.categorymenu'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
