# Generated by Django 5.0.1 on 2024-02-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0029_foods_ingredient_alter_foods_categorymenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateField()),
                ('number', models.IntegerField()),
                ('s_r', models.TextField()),
            ],
        ),
    ]
