# Generated by Django 5.0.1 on 2024-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0030_reser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reser',
            name='datetime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reser',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reser',
            name='s_r',
            field=models.TextField(null=True),
        ),
    ]
