# Generated by Django 5.0.1 on 2024-02-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0031_alter_reser_datetime_alter_reser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reser',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
