# Generated by Django 5.0.1 on 2024-02-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0034_alter_reser_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reser',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
