# Generated by Django 5.0.1 on 2024-02-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0037_alter_reser_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
