# Generated by Django 5.0.1 on 2024-02-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0038_reser_created_at_reser_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Profession', models.CharField(max_length=100)),
                ('say', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
