# Generated by Django 5.0.1 on 2024-02-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0041_clients_created_at_clients_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='image',
        ),
    ]
