# Generated by Django 5.0.1 on 2024-03-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0043_clients_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='image',
        ),
    ]
