# Generated by Django 5.0.1 on 2024-03-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0046_alter_clients_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
